FIX Add proxy configuration for embedded cURL requests
silverstripe/cwp-recipe-cms pull request #9
Opened 2018-06-18 07:39 UTC by robbieaverill

Issue: https://github.com/silverstripe/silverstripe-cms/issues/2168

Requires https://github.com/silverstripe/silverstripe-framework/pull/8194 and requires https://github.com/silverstripe/silverstripe-asset-admin/pull/795

2018-06-18 23:32 UTC, NightJar approved these changes
👌

2018-06-19 22:49 UTC, lukereative requested changes

2018-06-19 22:49 UTC, lukereative commented on app/_config/oembed.yml
> +      foo: bar
I assume this isn't supposed to be here

2018-06-19 22:50 UTC, robbieaverill commented on app/_config/oembed.yml
> +      foo: bar
Correct! Thanks 😆

2018-06-19 22:51 UTC, lukereative approved these changes

2018-06-19 23:44 UTC, merged